### ISSUE TITLE
Failed to activate the atom-ide-debugger-python package

### ISSUE THREAD

**Issue by djpremier** [facebook-atom/atom-ide-debugger-python#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-debugger-python](https://github.com/facebook-atom/atom-ide-debugger-python) package 0.7.1

### Stack Trace

Failed to activate the atom-ide-debugger-python package

```
At Cannot find module '../../../../nuclide-commons/nuclideUri'

Error: Cannot find module '../../../../nuclide-commons/nuclideUri'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_nuclideUri (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:46:74)
    at Activation._setProvidersForConnection (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:389:33)
    at Activation._disposables.default._uiModel.onProvidersUpdated (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:155:14)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DebuggerModel.addDebuggerProvider (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/DebuggerUiModel.js:94:19)
    at Activation.consumeDebuggerProvider (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/main.js:844:19)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:62:34)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:397:75)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:233:20)
    at measure (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.27.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.27.0/resources/app/src/package-manager.js:695:42)
    at /packages/sync-settings/lib/package-manager.coffee:167:25
    at exit (/packages/sync-settings/lib/package-manager.coffee:27:7)
    at triggerExitCallback (~/AppData/Local/atom/app-1.27.0/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.27.0/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -6:43.9.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:42.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-clock 0.1.16 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.11.2 
atom-live-server 2.2.0 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
chrome-color-picker 0.8.0 
dragon-fire-syntax 0.5.3 
file-header 1.13.9 
file-icons 2.1.20 
flex-tool-bar 2.0.2 
hey-pane 1.1.0 
ide-python 0.9.2 
kite 0.92.0 
markdown-writer 2.7.3 
minimap 4.29.8 
minimap-pigments 0.2.2 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
preview-inline 1.5.1 
python-debugger 0.2.0 
python-indent 1.1.5 
script 3.17.3 
sync-settings 0.8.6 
teletype 0.13.2 
tool-bar 1.1.7 
tool-bar-atom 1.7.0 
tool-bar-gui 2.0.2 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.3.1 
tool-bar-shortcuts 0.1.5 
toolbar-iconshortcuts 3.17.0 
```

**Comment by mostafaeweda** [comment]
@hansonw this seems coming from the `atom-ide-ui` sub-package not able to find `nuclide-commons/nuclideUri`? where does the `'../../../../nuclide-commons/nuclideUri'` resolved path come from?

**Comment by hansonw** [comment]
This seems like a bad install: try https://github.com/facebook-atom/atom-ide-ui/issues/64 to re-install `atom-ide-ui`. (as for where the relative paths come from - `nuclide-commons` requires are rewritten to be relative at build time. But that path should definitely exist in the release build.)
